---
- name: This playbook for Package Management
  hosts: 
    - linux

  pre_tasks:
    - debug: 
        msg: "Start Playbook"

  roles:
    - datadisk-7054
    - profile-7054
    - user-7054
    - webserver-7054

  post_tasks:
    - debug: 
        msg: "Playbook Completed Successfully"